import pandas as pd
df = pd.read_parquet(r'c:\jiya\big-data-scoring\data\output\trust_scores_kafka_demo\results_batch_0.parquet')
print('Output File Analysis')
print('=' * 60)
print(f'Shape: {df.shape}')
print(f'\nColumns: {df.columns.tolist()}')
print(f'\nFirst record:')
for col in df.columns:
    print(f'  {col}: {df.iloc[0][col]}')
print(f'\nTrust Score Statistics:')
print(df['trust_score'].describe())
print(f'\nAnomaly Detection:')
print(f'  Total records: {len(df)}')
print(f'  Anomalies detected: {df["is_anomaly"].sum()}')
print(f'  Anomaly rate: {df["is_anomaly"].mean() * 100:.1f}%')
print(f'\nSource Performance:')
print(df.groupby('source_id')['trust_score'].agg(['count', 'mean', 'min', 'max']))
